### ISSUE TITLE
Simple endpoint for prev, next and random

### ISSUE THREAD

**Issue by tdrayson** [whitep4nth3r/the-claw-webring-widget#5]
An idea would be to create 3 endpoints that are dynamic.

this moves away from the WC slightly but gives the ability for it to be “static” as the endpoint link auto redirects based on hostname. 

Alternatively a simplified wc that just has links and no list.

**Comment by whitep4nth3r** [comment]
I can add an option to show/hide the list on the web component.

The endpoint creation would mean more work to be done on the webring members' part. Some people who want to be part of the webring might not be confident developers and may not have the skills to drop those endpoints in etc.
