### ISSUE TITLE
A[a] error when including the widget

### ISSUE THREAD

**Issue by stuartlangridge** [whitep4nth3r/the-claw-webring-widget#9]
https://www.kryogenix.org/days/ shows the following error in Firefox and Chrome afaict:

Uncaught (in promise) TypeError: A[a] is undefined
    connectedCallback the-claw-webring-widget.mjs:49
    async* the-claw-webring-widget.mjs:114
[the-claw-webring-widget.mjs:formatted:49](https://the-claw-webring-widget.netlify.app/the-claw-webring-widget.mjs:formatted)

Not quite sure what the code there is doing; it's looking for my domain name. Is this a www.kryogenix.org vs kryogenix.org thing, perhaps?

**Comment by whitep4nth3r** [comment]
I know what the problem is! Your hostname is evaluated as `www.kryo...` — and in the data repo, there's no www. So it can't find the next/previous sites.

I could defensively code around this, or we could just update your entry in the data repo.

**Comment by stuartlangridge** [comment]
Seems to be fixed! What an excellently fast response :-) Thank you!
